var DENOMINATIONS = [
  { id: 0, numberOfZeros: 3, abbreviation: 'K', name: 'Thousand' },
  { id: 1, numberOfZeros: 6, abbreviation: 'M', name: 'Million' },
  { id: 2, numberOfZeros: 9, abbreviation: 'B', name: 'Billion' },
  { id: 3, numberOfZeros: 12, abbreviation: 'T', name: 'Trillion' },
  { id: 4, numberOfZeros: 15, abbreviation: 'Qd', name: 'Quadrillion' },
  { id: 5, numberOfZeros: 18, abbreviation: 'Qi', name: 'Quintillion' },
  { id: 6, numberOfZeros: 21, abbreviation: 'Sx', name: 'Sextillion' },
  { id: 7, numberOfZeros: 24, abbreviation: 'Sp', name: 'Septillion' },
  { id: 8, numberOfZeros: 27, abbreviation: 'Oc', name: 'Octillion' },
  { id: 9, numberOfZeros: 30, abbreviation: 'No', name: 'Nonillion' },
  { id: 10, numberOfZeros: 33, abbreviation: 'Dc', name: 'Decillion' },
  { id: 11, numberOfZeros: 36, abbreviation: 'UDc', name: 'Undecillion' },
  { id: 12, numberOfZeros: 39, abbreviation: 'DDc', name: 'Duodecillion' },
  { id: 13, numberOfZeros: 42, abbreviation: 'TDc', name: 'Tredecillion' },
  { id: 14, numberOfZeros: 45, abbreviation: 'QaDc', name: 'Quattuordecillion' },
  { id: 15, numberOfZeros: 48, abbreviation: 'QiDc', name: 'Quindecillion' },
  { id: 16, numberOfZeros: 51, abbreviation: 'SxDc', name: 'Sexdecillion' },
  { id: 17, numberOfZeros: 54, abbreviation: 'SpDc', name: 'Septendecillion' },
  { id: 18, numberOfZeros: 57, abbreviation: 'OcDc', name: 'Octodecillion' },
  { id: 19, numberOfZeros: 60, abbreviation: 'NDc', name: 'Novemdecillion' },
  { id: 20, numberOfZeros: 63, abbreviation: 'Vg', name: 'Vigintillion' },
  { id: 21, numberOfZeros: 66, abbreviation: 'UVg', name: 'Unvigintillion' },
  { id: 22, numberOfZeros: 69, abbreviation: 'DVg', name: 'Duovigintillion' },
  { id: 23, numberOfZeros: 72, abbreviation: 'TVg', name: 'Tresvigintillion' },
  { id: 24, numberOfZeros: 75, abbreviation: 'QaVg', name: 'Quattuorvigintillion' },
  { id: 25, numberOfZeros: 78, abbreviation: 'QiVg', name: 'Quinvigintillion' },
  { id: 26, numberOfZeros: 81, abbreviation: 'SxVg', name: 'Sexvigintillion' },
  { id: 27, numberOfZeros: 84, abbreviation: 'SpVg', name: 'Septenvigintillion' },
  { id: 28, numberOfZeros: 87, abbreviation: 'OcVg', name: 'Octovigintillion' },
  { id: 29, numberOfZeros: 90, abbreviation: 'NoVg', name: 'Novemvigintillion' },
  { id: 30, numberOfZeros: 93, abbreviation: 'Tg', name: 'Trigintillion' },
  { id: 31, numberOfZeros: 96, abbreviation: 'UTg', name: 'Untrigintillion' },
  { id: 32, numberOfZeros: 99, abbreviation: 'DTg', name: 'Duotrigintillion' },
  { id: 33, numberOfZeros: 102, abbreviation: 'TTg', name: 'Trestrigintillion' },
  { id: 34, numberOfZeros: 105, abbreviation: 'QaTg', name: 'Quattuortrigintillion' },
  { id: 35, numberOfZeros: 108, abbreviation: 'QiTg', name: 'Quintrigintillion' },
  { id: 36, numberOfZeros: 111, abbreviation: 'SxTg', name: 'Sextrigintillion' },
  { id: 37, numberOfZeros: 114, abbreviation: 'SpTg', name: 'Septrigintillion' },
  { id: 38, numberOfZeros: 117, abbreviation: 'OcTg', name: 'Octotrigintillion' },
  { id: 39, numberOfZeros: 120, abbreviation: 'NoTg', name: 'Novemtrigintillion' },
  { id: 40, numberOfZeros: 123, abbreviation: 'Qag', name: 'Quadragintillion' },
  { id: 41, numberOfZeros: 126, abbreviation: 'UQag', name: 'Unquadragintillion' },
  { id: 42, numberOfZeros: 129, abbreviation: 'DQag', name: 'Duoquadragintillion' },
  { id: 43, numberOfZeros: 132, abbreviation: 'TQag', name: 'Tresquadragintillion' },
  { id: 44, numberOfZeros: 135, abbreviation: 'QaQag', name: 'Quattuorquadragintillion' },
  { id: 45, numberOfZeros: 138, abbreviation: 'QiQag', name: 'Quinquadragintillion' },
  { id: 46, numberOfZeros: 141, abbreviation: 'SxQag', name: 'Sexquadragintillion' },
  { id: 47, numberOfZeros: 144, abbreviation: 'SpQag', name: 'Septenquadragintillion' },
  { id: 48, numberOfZeros: 147, abbreviation: 'OcQag', name: 'Octoquadragintillion' },
  { id: 49, numberOfZeros: 150, abbreviation: 'NoQag', name: 'Novemquadragintillion' },
  { id: 50, numberOfZeros: 153, abbreviation: 'Qig', name: 'Quinquagintillion' },
  { id: 51, numberOfZeros: 156, abbreviation: 'UQig', name: 'Unquinquagintillion' },
  { id: 52, numberOfZeros: 159, abbreviation: 'DQig', name: 'Duoquinquagintillion' },
  { id: 53, numberOfZeros: 162, abbreviation: 'TQig', name: 'Tresquinquagintillion' },
  { id: 54, numberOfZeros: 165, abbreviation: 'QaQig', name: 'Quattuorquinquagintillion' },
  { id: 55, numberOfZeros: 168, abbreviation: 'QiQig', name: 'Quinquinquagintillion' },
  { id: 56, numberOfZeros: 171, abbreviation: 'SxQig', name: 'Sexquinquagintillion' },
  { id: 57, numberOfZeros: 174, abbreviation: 'SpQig', name: 'Septenquinquagintillion' },
  { id: 58, numberOfZeros: 177, abbreviation: 'OcQig', name: 'Octoquinquagintillion' },
  { id: 59, numberOfZeros: 180, abbreviation: 'NoQig', name: 'Novemquinquagintillion' },
  { id: 60, numberOfZeros: 183, abbreviation: 'Sxg', name: 'Sexagintillion' },
  { id: 61, numberOfZeros: 186, abbreviation: 'USxg', name: 'Unsexagintillion' },
  { id: 62, numberOfZeros: 189, abbreviation: 'DSxg', name: 'Duosexagintillion' },
  { id: 63, numberOfZeros: 192, abbreviation: 'TSxg', name: 'Tressexagintillion' },
  { id: 64, numberOfZeros: 195, abbreviation: 'QdSxg', name: 'Quattuorsexagintillion' },
  { id: 65, numberOfZeros: 198, abbreviation: 'QiSxg', name: 'Quinsexagintillion' },
  { id: 66, numberOfZeros: 201, abbreviation: 'SxSxg', name: 'Sexsexagintillion' },
  { id: 67, numberOfZeros: 204, abbreviation: 'SpSxg', name: 'Septensexagintillion' },
  { id: 68, numberOfZeros: 207, abbreviation: 'OcSxg', name: 'Octosexagintillion' },
  { id: 69, numberOfZeros: 210, abbreviation: 'NoSxg', name: 'Novemsexagintillion' },
  { id: 70, numberOfZeros: 213, abbreviation: 'Spg', name: 'Septuagintillion' },
  { id: 71, numberOfZeros: 216, abbreviation: 'USpg', name: 'Unseptuagintillion' },
  { id: 72, numberOfZeros: 219, abbreviation: 'DSpg', name: 'Duoseptuagintillion' },
  { id: 73, numberOfZeros: 222, abbreviation: 'TSpg', name: 'Tresseptuagintillion' },
  { id: 74, numberOfZeros: 225, abbreviation: 'QaSpg', name: 'Quattuorseptuagintillion' },
  { id: 75, numberOfZeros: 228, abbreviation: 'QiSpg', name: 'Quinseptuagintillion' },
  { id: 76, numberOfZeros: 231, abbreviation: 'SxSpg', name: 'Sexseptuagintillion' },
  { id: 77, numberOfZeros: 234, abbreviation: 'SpSpg', name: 'Septenseptuagintillion' },
  { id: 78, numberOfZeros: 237, abbreviation: 'OcSpg', name: 'Octseptuagintillion' },
  { id: 79, numberOfZeros: 240, abbreviation: 'NoSpg', name: 'Novemseptuagintillion' },
  { id: 80, numberOfZeros: 243, abbreviation: 'Ocg', name: 'Octigintillion' },
  { id: 81, numberOfZeros: 246, abbreviation: 'UOcg', name: 'Unoctogintillion' },
  { id: 82, numberOfZeros: 249, abbreviation: 'DOcg', name: 'Duooctogintillion' },
  { id: 83, numberOfZeros: 252, abbreviation: 'TOcg', name: 'Tresoctogintillion' },
  { id: 84, numberOfZeros: 255, abbreviation: 'QaOcg', name: 'Quattuoroctogintillion' },
  { id: 85, numberOfZeros: 258, abbreviation: 'QiOcg', name: 'Quinoctogintillion' },
  { id: 86, numberOfZeros: 261, abbreviation: 'SxOcg', name: 'Sexoctogintillion' },
  { id: 87, numberOfZeros: 264, abbreviation: 'SpOcg', name: 'Septoctogintillion' },
  { id: 88, numberOfZeros: 267, abbreviation: 'OcOcg', name: 'Octooctogintillion' },
  { id: 89, numberOfZeros: 270, abbreviation: 'NoOcg', name: 'Novemoctogintillion' },
  { id: 90, numberOfZeros: 273, abbreviation: 'Nog', name: 'Nonagintillion' },
  { id: 91, numberOfZeros: 276, abbreviation: 'UNog', name: 'Unnonagintillion' },
  { id: 92, numberOfZeros: 279, abbreviation: 'DNog', name: 'Duononagintillion' },
  { id: 93, numberOfZeros: 282, abbreviation: 'TNog', name: 'Tresnonagintillion' },
  { id: 94, numberOfZeros: 285, abbreviation: 'QaNog', name: 'Quattuornonagintillion' },
  { id: 95, numberOfZeros: 288, abbreviation: 'QiNog', name: 'Quinnonagintillion' },
  { id: 96, numberOfZeros: 291, abbreviation: 'SxNog', name: 'Sexnonagintillion' },
  { id: 97, numberOfZeros: 294, abbreviation: 'SpNog', name: 'Septenonnonagintillion' },
  { id: 98, numberOfZeros: 297, abbreviation: 'OcNog', name: 'Octononagintillion' },
  { id: 99, numberOfZeros: 300, abbreviation: 'NoNog', name: 'Novemnonagintillion' },
  { id: 100, numberOfZeros: 303, abbreviation: 'C', name: 'Centillion' },
  { id: 101, numberOfZeros: 306, abbreviation: 'UC', name: 'Uncentillion' },
  { id: 102, numberOfZeros: 309, abbreviation: 'DC', name: 'Duocentillion' },
  { id: 103, numberOfZeros: 312, abbreviation: 'TC', name: 'Trescentillion' },
  { id: 104, numberOfZeros: 315, abbreviation: 'QaC', name: 'Quattuorcentillion' },
  { id: 105, numberOfZeros: 318, abbreviation: 'QiC', name: 'Quinquacentillion' },
  { id: 106, numberOfZeros: 321, abbreviation: 'SxC', name: 'Sexcentillion' },
  { id: 107, numberOfZeros: 324, abbreviation: 'SpC', name: 'Septencentillion' },
  { id: 108, numberOfZeros: 327, abbreviation: 'OcC', name: 'Octocentillion' },
  { id: 109, numberOfZeros: 330, abbreviation: 'NoC', name: 'Novemcentillion' },
  { id: 110, numberOfZeros: 333, abbreviation: 'Dc', name: 'Decicentillion' },
  { id: 111, numberOfZeros: 336, abbreviation: 'UDc', name: 'Undecicentillion' },
  { id: 112, numberOfZeros: 339, abbreviation: 'DDc', name: 'Duodecicentillion' },
  { id: 113, numberOfZeros: 342, abbreviation: 'TDc', name: 'Tredecicentillion' },
  { id: 114, numberOfZeros: 345, abbreviation: 'QaDc', name: 'Quattuordecicentillion' },
  { id: 115, numberOfZeros: 348, abbreviation: 'QiDc', name: 'Quindecicentillion' },
  { id: 116, numberOfZeros: 351, abbreviation: 'SxDc', name: 'Sexdecicentillion' },
  { id: 117, numberOfZeros: 354, abbreviation: 'SpDc', name: 'Septendecicentillion' },
  { id: 118, numberOfZeros: 357, abbreviation: 'OcDc', name: 'Octodecicentillion' },
  { id: 119, numberOfZeros: 360, abbreviation: 'NoDc', name: 'Novemdecicentillion' },
  { id: 120, numberOfZeros: 363, abbreviation: 'Vg', name: 'Viginticentillion' },
  { id: 121, numberOfZeros: 366, abbreviation: 'UVg', name: 'Unviginticentillion' },
  { id: 122, numberOfZeros: 369, abbreviation: 'DVg', name: 'Duoviginticentillion' },
  { id: 123, numberOfZeros: 372, abbreviation: 'TVg', name: 'Tresviginticentillion' },
  { id: 124, numberOfZeros: 375, abbreviation: 'QaVg', name: 'Quattuorviginticentillion' },
  { id: 125, numberOfZeros: 378, abbreviation: 'QiVg', name: 'Quinviginticentillion' },
  { id: 126, numberOfZeros: 381, abbreviation: 'SxVg', name: 'Sexviginticentillion' },
  { id: 127, numberOfZeros: 384, abbreviation: 'SpVg', name: 'Septenviginticentillion' },
  { id: 128, numberOfZeros: 387, abbreviation: 'OcVg', name: 'Octoviginticentillion' },
  { id: 129, numberOfZeros: 390, abbreviation: 'NoVg', name: 'Novemviginticentillion' },
  { id: 130, numberOfZeros: 393, abbreviation: 'Tg', name: 'Trigintacentillion' },
  { id: 131, numberOfZeros: 396, abbreviation: 'UTg', name: 'Untrigintacentillion' },
  { id: 132, numberOfZeros: 399, abbreviation: 'DTg', name: 'Duotrigintacentillion' },
  { id: 133, numberOfZeros: 402, abbreviation: 'TTg', name: 'Trestrigintacentillion' },
  { id: 134, numberOfZeros: 405, abbreviation: 'QaTg', name: 'Quattuortrigintacentillion' },
  { id: 135, numberOfZeros: 408, abbreviation: 'QiTg', name: 'Quintrigintacentillion' },
  { id: 136, numberOfZeros: 411, abbreviation: 'SxTg', name: 'Sextrigintacentillion' },
  { id: 137, numberOfZeros: 414, abbreviation: 'SpTg', name: 'Septentrigintacentillion' },
  { id: 138, numberOfZeros: 417, abbreviation: 'OcTg', name: 'Octotrigintacentillion' },
  { id: 139, numberOfZeros: 420, abbreviation: 'NoTg', name: 'Novemtrigintacentillion' },
  { id: 140, numberOfZeros: 423, abbreviation: 'QagC', name: 'Quadragintacentillion' },
  { id: 141, numberOfZeros: 426, abbreviation: 'UQagC', name: 'Unquadragintacentillion' },
  { id: 142, numberOfZeros: 429, abbreviation: 'DQagC', name: 'Duoquadragintacentillion' },
  { id: 143, numberOfZeros: 432, abbreviation: 'TQagC', name: 'Tresquadragintacentillion' },
  { id: 144, numberOfZeros: 435, abbreviation: 'QaQagC', name: 'Quattuorquadragintacentillion' },
  { id: 145, numberOfZeros: 438, abbreviation: 'QiQagC', name: 'Quinquadragintacentillion' },
  { id: 146, numberOfZeros: 441, abbreviation: 'SxQagC', name: 'Sexquadragintacentillion' },
  { id: 147, numberOfZeros: 444, abbreviation: 'SpQagC', name: 'Septenquadragintacentillion' },
  { id: 148, numberOfZeros: 447, abbreviation: 'OcQagC', name: 'Octoquadragintacentillion' },
  { id: 149, numberOfZeros: 450, abbreviation: 'NoQagC', name: 'Novemquadragintacentillion' },
  { id: 150, numberOfZeros: 453, abbreviation: 'QigC', name: 'Quinquagintacentillion' },
  { id: 151, numberOfZeros: 456, abbreviation: 'UQigC', name: 'Unquinquagintacentillion' },
  { id: 152, numberOfZeros: 459, abbreviation: 'DQigC', name: 'Duoquinquagintacentillion' },
  { id: 153, numberOfZeros: 462, abbreviation: 'TQigC', name: 'Tresquinquagintacentillion' },
  { id: 154, numberOfZeros: 465, abbreviation: 'QaQigC', name: 'Quattuorquinquagintacentillion' },
  { id: 155, numberOfZeros: 468, abbreviation: 'QiQigC', name: 'Quinquinquagintacentillion' },
  { id: 156, numberOfZeros: 471, abbreviation: 'SxQigC', name: 'Sexquinquagintacentillion' },
  { id: 157, numberOfZeros: 474, abbreviation: 'SpQigC', name: 'Septenquinquagintacentillion' },
  { id: 158, numberOfZeros: 477, abbreviation: 'OcQigC', name: 'Octoquinquagintacentillion' },
  { id: 159, numberOfZeros: 480, abbreviation: 'NoQigC', name: 'Novemquinquagintacentillion' },
  { id: 160, numberOfZeros: 483, abbreviation: 'SxgC', name: 'Sexagintacentillion' },
  { id: 161, numberOfZeros: 486, abbreviation: 'USxgC', name: 'Unsexagintacentillion' },
  { id: 162, numberOfZeros: 489, abbreviation: 'DSxgC', name: 'Duosexagintacentillion' },
  { id: 163, numberOfZeros: 492, abbreviation: 'TSxgC', name: 'Tresexagintacentillion' },
  { id: 164, numberOfZeros: 495, abbreviation: 'QaSxgC', name: 'Quattuorsexagintacentillion' },
  { id: 165, numberOfZeros: 498, abbreviation: 'QiSxgC', name: 'Quinsexagintacentillion' },
  { id: 166, numberOfZeros: 501, abbreviation: 'SxSxgC', name: 'Sexsexagintacentillion' },
  { id: 167, numberOfZeros: 504, abbreviation: 'SpSxgC', name: 'Septensexagintacentillion' },
  { id: 168, numberOfZeros: 507, abbreviation: 'OcSxgC', name: 'Octosexagintacentillion' },
  { id: 169, numberOfZeros: 510, abbreviation: 'NoSxgC', name: 'Novemsexagintacentillion' },
  { id: 170, numberOfZeros: 513, abbreviation: 'SpgC', name: 'Septuagintacentillion' },
  { id: 171, numberOfZeros: 516, abbreviation: 'USpgC', name: 'Unseptuagintacentillion' },
  { id: 172, numberOfZeros: 519, abbreviation: 'DSpgC', name: 'Duoseptuagintacentillion' },
  { id: 173, numberOfZeros: 522, abbreviation: 'TSpgC', name: 'Treseptuagintacentillion' },
  { id: 174, numberOfZeros: 525, abbreviation: 'QaSpgC', name: 'Quattuorseptuagintacentillion' },
  { id: 175, numberOfZeros: 528, abbreviation: 'QiSpgC', name: 'Quinseptuagintacentillion' },
  { id: 176, numberOfZeros: 531, abbreviation: 'SxSpgC', name: 'Sexseptuagintacentillion' },
  { id: 177, numberOfZeros: 534, abbreviation: 'SpSpgC', name: 'Septenseptuagintacentillion' },
  { id: 178, numberOfZeros: 537, abbreviation: 'OcSpgC', name: 'Octoseptuagintacentillion' },
  { id: 179, numberOfZeros: 540, abbreviation: 'NoSpgC', name: 'Novemseptuagintacentillion' },
  { id: 180, numberOfZeros: 543, abbreviation: 'OcgC', name: 'Octogintacentillion' },
  { id: 181, numberOfZeros: 546, abbreviation: 'UOcgC', name: 'Unoctogintacentillion' },
  { id: 182, numberOfZeros: 549, abbreviation: 'DOcgC', name: 'Duooctogintacentillion' },
  { id: 183, numberOfZeros: 552, abbreviation: 'TOcgC', name: 'Tresoctogintacentillion' },
  { id: 184, numberOfZeros: 555, abbreviation: 'QaOcgC', name: 'Quattuoroctogintacentillion' },
  { id: 185, numberOfZeros: 558, abbreviation: 'QiOcgC', name: 'Quinoctogintacentillion' },
  { id: 186, numberOfZeros: 561, abbreviation: 'SxOcgC', name: 'Sexoctogintacentillion' },
  { id: 187, numberOfZeros: 564, abbreviation: 'SpOcgC', name: 'Septenoctogintacentillion' },
  { id: 188, numberOfZeros: 567, abbreviation: 'OcOcgC', name: 'Octooctogintacentillion' },
  { id: 189, numberOfZeros: 570, abbreviation: 'NoOcgC', name: 'Novenoctogintacentillion' },
  { id: 190, numberOfZeros: 573, abbreviation: 'NogC', name: 'Nonagintacentillion' },
  { id: 191, numberOfZeros: 576, abbreviation: 'UNogC', name: 'Unnonagintacentillion' },
  { id: 192, numberOfZeros: 579, abbreviation: 'DNogC', name: 'Duononagintacentillion' },
  { id: 193, numberOfZeros: 582, abbreviation: 'TNogC', name: 'Tresnonagintacentillion' },
  { id: 194, numberOfZeros: 585, abbreviation: 'QaNogC', name: 'Quattuornonagintacentillion' },
  { id: 195, numberOfZeros: 588, abbreviation: 'QiNogC', name: 'Quinnonagintacentillion' },
  { id: 196, numberOfZeros: 591, abbreviation: 'SxNogC', name: 'Sexnonagintacentillion' },
  { id: 197, numberOfZeros: 594, abbreviation: 'SpNogC', name: 'Septennonagintacentillion' },
  { id: 198, numberOfZeros: 597, abbreviation: 'OcNogC', name: 'Octononagintacentillion' },
  { id: 199, numberOfZeros: 600, abbreviation: 'NoNogC', name: 'Novennonagintacentillion' },
  { id: 200, numberOfZeros: 603, abbreviation: 'DuC', name: 'Ducentillion' },
  { id: 201, numberOfZeros: 606, abbreviation: 'UDuC', name: 'Unducentillion' },
  { id: 202, numberOfZeros: 609, abbreviation: 'DDuC', name: 'Duoducentillion' },
  { id: 203, numberOfZeros: 612, abbreviation: 'TDuC', name: 'Tresducentillion' },
  { id: 204, numberOfZeros: 615, abbreviation: 'QaDuC', name: 'Quattuorducentillion' },
  { id: 205, numberOfZeros: 618, abbreviation: 'QiDuC', name: 'Quinducentillion' },
  { id: 206, numberOfZeros: 621, abbreviation: 'SxDuC', name: 'Sexducentillion' },
  { id: 207, numberOfZeros: 624, abbreviation: 'SpDuC', name: 'Septenducentillion' },
  { id: 208, numberOfZeros: 627, abbreviation: 'OcDuC', name: 'Octoducentillion' },
  { id: 209, numberOfZeros: 630, abbreviation: 'NoDuC', name: 'Novenducentillion' },
  { id: 210, numberOfZeros: 633, abbreviation: 'DeDuC', name: 'Deciducentillion' },
  { id: 211, numberOfZeros: 636, abbreviation: 'UDeDuC', name: 'Undeciducentillion' },
  { id: 212, numberOfZeros: 639, abbreviation: 'DDeDuC', name: 'Duodeciducentillion' },
  { id: 213, numberOfZeros: 642, abbreviation: 'TDeDuC', name: 'Tredeciducentillion' },
  { id: 214, numberOfZeros: 645, abbreviation: 'QaDeDuC', name: 'Quattuordeciducentillion' },
  { id: 215, numberOfZeros: 648, abbreviation: 'QiDeDuC', name: 'Quindeciducentillion' },
  { id: 216, numberOfZeros: 651, abbreviation: 'SxDeDuC', name: 'Sexdeciducentillion' },
  { id: 217, numberOfZeros: 654, abbreviation: 'SpDeDuC', name: 'Septendeciducentillion' },
  { id: 218, numberOfZeros: 657, abbreviation: 'OcDeDuC', name: 'Octodeciducentillion' },
  { id: 219, numberOfZeros: 660, abbreviation: 'NoDeDuC', name: 'Novemdeciducentillion' },
  { id: 220, numberOfZeros: 663, abbreviation: 'VDuC', name: 'Vigintiducentillion' },
]

$(() => {


  const getCheddarAbbr = () => {
    const numberOfZeros = cheddar.toString().length - 1
    const result = DENOMINATIONS.filter((denomination) => {
      console.log({
        'denomination.numberOfZeros':denomination.numberOfZeros,
        numberOfZeros
      })
      return denomination.numberOfZeros >= numberOfZeros && denomination.numberOfZeros <= numberOfZeros + 2
    })
    if (!result || !result[0]) {
      return ''
    }
    return result[0].abbreviation
  }

  let cheddar = 9999
  $('#cheddar').text(cheddar)
  $('#cheddar-abbr').text(getCheddarAbbr(cheddar))

  const mainTick = 1000
  const mainThread = setInterval(() => {
    cheddar++

    $('#cheddar').text(cheddar)
    $('#cheddar-abbr').text(getCheddarAbbr(cheddar))
  }, mainTick)

})
