<?php $this->renderPartial('head'); ?>
<article class="xxs-col" data-page="page-resume">
  <?php $this->renderPartial('header'); ?>

  <section class="max-width-fluid xxs-col">

    <nav class="xxs-col <?= $this->t->Config->local ? '' : 'hidden'; ?> no-print">
      <menu class="xxs-col">
        <li><a href="<?= $this->t->Helpers::getLink('/page/resume/'); ?>">Senior Software Developer</a></li>
        <li><a href="<?= $this->t->Helpers::getLink('/page/resume/?title=Senior%20Support%20Engineer'); ?>">Senior Support Engineer</a></li>
      </menu>
    </nav>

    <section class="xxs-col">
      <hgroup class="xxs-col text-center">
        <h1 class="xxs-col">Dustin Zeigler</h1>
        <p class="xxs-col"><?= $this->t->Controller->getResumeTitle(); ?></p>
      </hgroup>
    </section>

    <section class="xxs-col">
      <hgroup class="xxs-col text-center text-uppercase">
        <h2 class="xxs-col">Profile</h2>
      </hgroup>
      <section class="xxs-col">
        <p class="xxs-col text-center"><?= $this->t->Controller->getResumeProfile(); ?></p>
      </section>
    </section>

    <section class="xxs-col md-row">
      <aside class="xxs-col md-col-1">

        <section class="xxs-col">
          <hgroup class="xxs-col text-center text-uppercase">
            <h2 class="xxs-col">Contact</h2>
          </hgroup>
          <section class="xxs-col">
            <address class="xxs-col font-normal">
              <ul class="xxs-col list-style-none">
                <li><a href="tel:+15737895757" title="Call Me">+1 (573) 789-5757</a></li>
                <li><a href="mailto:dustin.zeigler@live.com" title="Email Me">dustin.zeigler@live.com</a></li>
                <li>1307 Sandra Ave<br>Apt B<br>Warrensburg, MO. 64093</li>
                <li><a href="https://www.linkedin.com/in/zeiglerd/" title="Visit On LinkedIn">https://www.linkedin.com/in/zeiglerd/</a></li>
              </ul>
            </address>
          </section>
        </section>

        <section class="xxs-col">
          <hgroup class="xxs-col text-center text-uppercase">
            <h2 class="xxs-col">Education</h2>
          </hgroup>
          <section class="xxs-col">
            <ul class="xxs-col list-style-none">
              <li>
                <hgroup class="xxs-col text-center">
                  <p class="xxs-col">February 2017</p>
                  <h3 class="xxs-col">BSc Web Design and Development</h3>
                  <p class="xxs-col">Full Sail University</p>
                </hgroup>
              </li>
            </ul>
          </section>
        </section>

        <section class="xxs-col">
          <hgroup class="xxs-col text-center text-uppercase">
            <h2 class="xxs-col">Key Skills</h2>
          </hgroup>
          <section class="xxs-col">
            <p class="xxs-col">Seven years of industry experience with:</p>
            <ul class="xxs-col">
              <?= $this->t->Controller->generateKeySkills(); ?>
            </ul>
          </section>
        </section>

        <section class="xxs-col">
          <hgroup class="xxs-col text-center text-uppercase">
            <h2 class="xxs-col">Additional Skills</h2>
          </hgroup>
          <section class="xxs-col">
            <p class="xxs-col">Some experience with:</p>
            <ul class="xxs-col">
              <?= $this->t->Controller->generateAdditionalSkills(); ?>
            </ul>
          </section>
        </section>
      </aside>

      <main class="xxs-col md-col-2 lg-col-3">
        <hgroup class="xxs-col text-center text-uppercase">
          <h2 class="xxs-col">Professional Experience</h2>
        </hgroup>

        <article class="xxs-col">
          <hgroup class="xxs-col text-center">
            <h3 class="xxs-col">Senior Software Developer</h3>
            <p class="xxs-col">Boats Group — Miami, FL — Remote</p>
            <p class="xxs-col">March 2022 — May 2024 — Full-time</p>
          </hgroup>
          <section class="xxs-col">
            <ul class="xxs-col">
              <li>
                <p>This role heavily revolved around the product and feature development of key projects, including:</p>
                <ul>
                  <li>Updating an ad prebid API to use a new source for GEO data, as well as writing a cronjob to update ad prebid data regularly, from a third-party source.</li>
                  <li>Helping to integrate CAS updates to support SSO for employees.</li>
                  <li>Creating a new React web app to replace a legacy lead delivery tool (written in Java) for customers.</li>
                  <li>Investigated slow-running queries, and wrote archiving procedures to remove outdated and irrelevant rows (1-billion+ across dozens of tables), greatly boosting MySQL query performance of over a half-dozen Java services and monolithic web apps.</li>
                  <li>A UI redesign project of admin and inventory management pages (monolithic Java + Grails web app).</li>
                </ul>
              </li>
              <li>Later this role saw a shift to a healthy mix of feature and M&S work (Node.js and Java maintenance).</li>
              <li>Tasked with bug hunting and squashing for escalated — high-priority — tickets.</li>
              <li>Identified additional poor performance in MySQL queries and added a few indices to help alleviate these issues.</li>
              <li>Helped to identify timezone issues (PST vs. UTC) between web apps and sources of truth.</li>
              <li>Upgraded a half-dozen Node.js 14.x and 10.x projects (APIs, libraries, and React web apps) to Node.js 20.</li>
              <li>Helped to manage ticket backlogs (preparation, prioritization, etc.), set expectations with key stakeholders, as well as led some team meetings when our development manager was otherwise preoccupied.</li>
              <li>Supported the training and onboarding of new team members.</li>
            </ul>
          </section>
        </article>

        <article class="xxs-col">
          <hgroup class="xxs-col text-center">
            <h3 class="xxs-col">Software Developer</h3>
            <p class="xxs-col">Boats Group — Miami, FL — On-site</p>
            <p class="xxs-col">March 2019 — March 2022 — Full-time</p>
          </hgroup>
          <section class="xxs-col">
            <ul class="xxs-col">
              <li>This role saw me shift to predominately an M&S workload in Node.js APIs (dozens of microservices); but also some monolithic Java web apps (Grails and custom frameworks).</li>
              <li>
                <p>Wrote a new scalable RESTful inventory API (Node.js + hapi Framework) as a microservice, which surfaced — both internally to our systems and externally to customers (using Kong API Gateway) — data indexed into Elasticsearch. This included:</p>
                <ul>
                  <li>Setting product expectations with external customers and stakeholders and communicating progress.</li>
                  <li>
                    <p>Creating:</p>
                    <ul>
                      <li>An SQS queue to enqueue inventory items needing to be indexed.</li>
                      <li>A scalable Lambda to digest the SQS queue and put items into Elasticsearch.</li>
                      <li>A DLQ to retry failures in the Lambda.</li>
                      <li>EventBridge events to watch for failures end-to-end.</li>
                      <li>All infrastructure as code using Terraform (IaC).</li>
                      <li>Jenkins jobs to deploy the API and Lambda to QA and Production environments.</li>
                      <li>Documentation and providing IT support for external development team's implementation of our service.</li>
                    </ul>
                  </li>
                  <li>Refactoring of pre-existing internal systems to ensure compatibility with changes.</li>
                </ul>
              </li>
              <li>Began full-time remote work in late 2019.</li>
              <li>Later in this team — much like my time in UI Development — I took on a lead developer role, managing ticket backlogs (preparation, prioritization, etc.), as well as leading some team meetings when our development manager was otherwise preoccupied.</li>
              <li>Upgraded dozens of Node.js 0.x, 4.x, and 10.x projects (APIs, libraries, and React web apps) to Node.js 14.</li>
            </ul>
          </section>
        </article>

        <article class="xxs-col pagebreak">
          <hgroup class="xxs-col text-center">
            <h3 class="xxs-col">UI Developer</h3>
            <p class="xxs-col">Boats Group — Miami, FL — On-site</p>
            <p class="xxs-col">July 2017 — March 2019 — Full-time</p>
          </hgroup>
          <section class="xxs-col">
            <ul class="xxs-col">
              <li>Worked hand-in-hand with the backend development team to generate SASS templates for a WordPress custom multisite platform that serviced 500+ customer websites.</li>
              <li>Pushed for new standards (component reusability, HTML5 semantics, CSS3 pseudo-selectors, SASS variables/functions/mixins, etc.) to be enforced.</li>
              <li>Later I became a full-stack developer in this team, working on the custom WordPress platform (PHP / Zend framework), integrating a new inventory API, and contributing to many of the custom WordPress plugins.</li>
              <li>Performed maintenance on the website generator tool (Node.js + Express) when it fell over and the knowledge from previous developers was no longer available.</li>
              <li>
                <p>I began leading a small development team of four as the company grew and the platform implementation team expanded. This included responsibilities like:</p>
                <ul>
                  <li>Ticket creation (Jira) for upcoming projects.</li>
                  <li>Organizing team meetings to review tickets before upcoming sprints.</li>
                  <li>Leading biweekly sprint review calls.</li>
                  <li>Delivering team 'Wins' at our weekly, 'Fridays are for Winners' meetings.</li>
                </ul>
              </li>
            </ul>
          </section>
        </article>

        <article class="xxs-col">
          <hgroup class="xxs-col text-center">
            <h3 class="xxs-col">Technical Support Representative</h3>
            <p class="xxs-col">Boats Group — Miami, FL — On-site</p>
            <p class="xxs-col">June 2017 — July 2017 — Full-time</p>
          </hgroup>
          <section class="xxs-col">
            <ul class="xxs-col">
              <li>Many tickets required updating KB articles, communicating across multiple account managers, development teams, managers, and product owners, and MySQL entries.</li>
              <li>Managed and triaged all incoming queries for internal and external customers.</li>
              <li>Provide product support and training to account managers, sales reps, and external customers.</li>
              <li>Clearly and concisely reported issues (resolved or not) through Jira, keeping issues in priority order, and setting expectations with key stakeholders.</li>
            </ul>
          </section>
        </article>

        <article class="xxs-col">
          <hgroup class="xxs-col text-center">
            <h3 class="xxs-col">Lead Back-end Developer</h3>
            <p class="xxs-col">Bilder — Greater Chicago Area — Remote</p>
            <p class="xxs-col">June 2016 — March 2017 — Freelance</p>
          </hgroup>
          <section class="xxs-col">
            <ul class="xxs-col">
              <li>A unique crowd-funding platform for universities, their students, and their communities.</li>
              <li>Planned, developed, and maintained back-end architecture for a web app.</li>
              <li>Created database schemas (MongoDB) to store projects, users, funding, etc.</li>
              <li>Created a secured RESTful API (Node.js + Express) to surface stored data safely.</li>
              <li>Helped implement an algorithm, to determine contributor impact across projects, based on GEO location.</li>
              <li>Worked closely with the design and front-end teams, especially during the planning stages, to ensure API payloads (input and output) would only accept correct and relevant data.</li>
            </ul>
          </section>
        </article>

        <article class="xxs-col">
          <hgroup class="xxs-col text-center">
            <h3 class="xxs-col">Full-stack Web Developer and DB Admin</h3>
            <p class="xxs-col">ContegoPrint — Remote</p>
            <p class="xxs-col">April 2012 — December 2014 — Freelance</p>
          </hgroup>
          <section class="xxs-col">
            <ul class="xxs-col">
              <li>A SaaS and eCommerce platform that allowed for the management and sale of author-published eBooks.</li>
              <li>Helped to develop a patented procedure to protect the integrity of eBooks made available on the platform.</li>
              <li>Created and managed database schemas (MySQL) to store authors, eBooks, authentication codes, customers, sales, etc.</li>
              <li>
                <p>Designed and developed the front-facing web apps (PHP, MVC, CSS3, jQuery, MySQL, PDO):</p>
                <ul>
                  <li>Company website.</li>
                  <li>Sales and inventory portals for customers.</li>
                  <li>eBook management portal for authors (CRUD app with PayPal Store integration).</li>
                  <li>Responsible for eBook authorization key generation, storage security (MD5 + random hash), and delivery after purchase.</li>
                </ul>
              </li>
            </ul>
          </section>
        </article>

      </main>
    </section>

    <section class="xxs-col no-print">
      <hgroup class="xxs-col text-center text-uppercase">
        <h2 class="xxs-col">View this — and My Site — Online!</h2>
      </hgroup>
      <section class="xxs-col">
        <img class="xxs-col" src="/images/templates/zeiglerd-theme/views/page/resume-qr-code.svg" alt="QR code" />
      </section>
      <section class="xxs-col">
        <p class="break-word text-center">Or check out the source code on GitHub:<br><a href="https://github.com/zeiglerd/zeiglerd.com/tree/main/src/templates/zeiglerd-theme/views/page">https://github.com/zeiglerd/zeiglerd.com/tree/main<br>/src/templates/zeiglerd-theme/views/page</a></p>
      </section>
    </section>

    <section class="xxs-col">
      <section class="xxs-col">
        <p class="xxs-col text-right">v4.0.1</p>
      </section>
    </section>

  </section>
  <?php $this->renderPartial('footer'); ?>
</article>
<?php $this->renderPartial('foot'); ?>
