<?php $this->renderPartial('head'); ?>
<?php $this->renderPartial('header'); ?>
<article data-page="post-resume">

  <section class="xs-col">
    <hgroup class="xs-col text-center">
      <h1 class="xs-col">Dustin Zeigler</h1>
      <p class="xs-col">Senior Software Developer</p>
    </hgroup>
  </section>

  <section class="xs-col">
    <hgroup class="xs-col text-center text-uppercase">
      <h2 class="xs-col">Profile</h2>
    </hgroup>
    <section class="xs-col">
      <p class="xs-col text-center">Software developer with 7 years of SaaS industry experience — working predominantly as a full-stack web developer — within a JavaScript environment, leveraging cloud-based computing for infrastructure solutions, and working alongside front-end designers to create web applications utilizing JS, HTML5, and CSS3.</p>
    </section>
  </section>

  <section class="xs-col md-row">
    <aside class="xs-col md-col-1">

      <section class="xs-col">
        <hgroup class="xs-col text-center text-uppercase">
          <h2 class="xs-col">Contact</h2>
        </hgroup>
        <section class="xs-col">
          <address class="xs-col font-normal">
            <ul class="xs-col list-style-none">
              <li><a href="tel:+15737895757" title="Call Me">+1 (573) 789-5757</a></li>
              <li><a href="mailto:dustin.zeigler@live.com" title="Email Me">dustin.zeigler@live.com</a></li>
              <li>1307 Sandra Ave<br>Apt B<br>Warrensburg, MO. 64093</li>
              <li><a href="https://www.linkedin.com/in/zeiglerd/" title="Visit On LinkedIn">https://www.linkedin.com/in/zeiglerd/</a></li>
            </ul>
          </address>
        </section>
      </section>

      <section class="xs-col">
        <hgroup class="xs-col text-center text-uppercase">
          <h2 class="xs-col">Education</h2>
        </hgroup>
        <section class="xs-col">
          <ul class="xs-col list-style-none">
            <li>
              <hgroup class="xs-col text-center">
                <p class="xs-col">February 2017</p>
                <h3 class="xs-col">BSc Web Design and Development</h3>
                <p class="xs-col">Full Sail University</p>
              </hgroup>
            </li>
          </ul>
        </section>
      </section>

      <section class="xs-col">
        <hgroup class="xs-col text-center text-uppercase">
          <h2 class="xs-col">Key Skills</h2>
        </hgroup>
        <section class="xs-col">
          <p class="xs-col">7 years of industry experience with the following:</p>
          <ul class="xs-col">
            <li>
              <p>JavaScript (<a href="https://ecma-international.org/" title="More About ECMAScript">ECMAScript</a>, MJS, CJS)</p>
              <ul>
                <li><p><a href="https://nodejs.org/en" title="More About Node.js">Node.js</a></p>
                  <ul>
                    <li><a href="https://hapi.dev/" title="More About hapi">hapi Framework</a></li>
                    <li><a href="https://axios-http.com/" title="More About Axios">Axios</a></li>
                    <li>
                      <p><a href="https://react.dev/" title="More About React">React</a></p>
                      <ul>
                        <li>Component Lifecycle</li>
                        <li>Functional Components</li>
                        <li>JavaScript XML (JSX)</li>
                        <li><a href="https://react-redux.js.org/" title="More About React">Redux</a></li>
                        <li>Server-Side Rendering</li>
                        <li>State Management</li>
                      </ul>
                    </li>
                    <li>Lazy Loading</li>
                    <li>Tree Shaking</li>
                    <li><a href="https://gruntjs.com/" title="More About Grunt.js">Grunt.js</a></li>
                    <li><a href="https://lodash.com/" title="More About Lodash">Lodash</a></li>
                  </ul>
                </li>
                <li>Unit Testing with <a href="https://hapi.dev/module/lab/" title="More About @hapi/lab">@hapi/lab</a>, <a href="https://hapi.dev/module/code/" title="More About @hapi/code">@hapi/code</a>, and <a href="https://jestjs.io/" title="More About Jest">Jest</a></li>
                <li>
                  <p><a href="https://jquery.com/" title="More About jQuery">jQuery</a> (when not in React)</p>
                  <ul>
                    <li><a href="https://api.jquery.com/jQuery.ajax/" title="More About AJAX">AJAX</a></li>
                  </ul>
                </li>
              </ul>
            </li>
            <li>Classical (OOP) and Prototypal Inheritance</li>
            <li>Factory Classes and Methods</li>
            <li>ADA Compliance</li>
            <li>HTML5 Hierarchy and Semantics</li>
            <li><a href="https://sass-lang.com/" title="More About SASS">SASS</a>, <a href="https://lesscss.org/" title="More About LESS">LESS</a>, and CSS3</li>
            <li><a href="https://swagger.io/specification/" title="More About Swagger">Swagger</a> (OpenAPI Specification)</li>
            <li><a href="https://www.terraform.io/" title="More About Terraform">Terraform</a> (Infrastructure as Code)</li>
            <li>Agile Development Processes</li>
            <li>Feature Branch Workflow</li>
            <li>Test Driven Design</li>
            <li>Leadership of a Small Development Team (four members)</li>
            <li>Training and Onboarding New Staff Members</li>
            <li>
              <p>Amazon (AWS)</p>
              <ul>
                <li><a href="https://aws.amazon.com/batch/" title="More About Batch">Batch</a></li>
                <li><a href="https://aws.amazon.com/ec2/" title="More About EC2">EC2</a></li>
                <li><a href="https://aws.amazon.com/ecs/" title="More About ECS">ECS</a></li>
                <li><a href="https://aws.amazon.com/lambda/" title="More About Lambda">Lambda</a></li>
                <li><a href="https://aws.amazon.com/rds/" title="More About RDS">RDS</a></li>
                <li><a href="https://aws.amazon.com/s3/" title="More About S3">S3</a></li>
                <li><a href="https://aws.amazon.com/security/" title="More About Security">Security</a></li>
                <li><a href="https://aws.amazon.com/sqs/" title="More About SQS">SQS</a></li>
                <li><a href="https://aws.amazon.com/systems-manager/features/#Parameter_Store" title="More About SSM">SSM</a></li>
              </ul>
            </li>
            <li><a href="https://www.mysql.com/" title="More About MySQL">MySQL</a> Databases</li>
            <li><a href="https://www.elastic.co/" title="More About Elasticsearch">Elasticsearch</a> Indices</li>
            <li>Monolithic Java Web Apps and APIs (<a href="https://grails.org/" title="Grails">Grails</a> and Custom Frameworks)</li>
            <li>Monolithic PHP Web Apps and APIs (<a href="https://framework.zend.com/" title="More About Zend Framework">Zend</a> and Custom Frameworks)</li>
            <li><a href="https://git-scm.com/" title="More About Git">Git</a>, <a href="https://github.com/" title="More About GitHub">GitHub</a>, and <a href="https://bitbucket.org/product/" title="More About Bitbucket">Bitbucket</a></li>
            <li><a href="https://semver.org/" title="More About SemVer">Semantic Versioning</a></li>
          </ul>
        </section>
      </section>

      <section class="xs-col">
        <hgroup class="xs-col text-center text-uppercase">
          <h2 class="xs-col">Further Skills</h2>
        </hgroup>
        <section class="xs-col">
          <p class="xs-col">Some experience with the following:</p>
          <ul class="xs-col">
            <li><a href="https://reactnative.dev/" title="More About Express">React Native</a></li>
            <li><a href="https://www.typescriptlang.org/" title="More About TypeScript">TypeScript</a></li>
            <li><a href="https://expressjs.com/" title="More About Express">Express</a></li>
            <li>
              <p>Amazon (AWS)</p>
              <ul>
                <li><a href="https://aws.amazon.com/api-gateway/" title="More About API Gateway">API Gateway</a></li>
                <li><a href="https://aws.amazon.com/cli/" title="More About CLI">CLI</a></li>
                <li><a href="https://aws.amazon.com/documentdb/" title="More About DocumentDB">DocumentDB</a></li>
                <li><a href="https://aws.amazon.com/sns/" title="More About SNS">SNS</a></li>
                <li><a href="https://aws.amazon.com/step-functions/" title="More About Step Functions">Step Functions</a></li>
              </ul>
            </li>
            <li>Regular Expressions</li>
            <li><a href="https://konghq.com/" title="More About Kong API Gateway">Kong API Gateway</a></li>
            <li><a href="https://memcached.org/" title="More About Memcached">Memcached</a></li>
            <li><a href="https://www.mongodb.com/" title="More About MongoDB">MongoDB</a></li>
            <li>Bash and ZSH</li>
            <li>Ubuntu Server</li>
            <li><a href="https://wordpress.com/" title="More About WordPress">WordPress</a> and WordPress Multisite</li>
          </ul>
        </section>
      </section>
    </aside>

    <main class="xs-col md-col-2 lg-col-3">
      <hgroup class="xs-col text-center text-uppercase">
        <h2 class="xs-col">Professional Experience</h2>
      </hgroup>

      <article class="xs-col">
        <hgroup class="xs-col text-center">
          <h3 class="xs-col">Senior Software Developer</h3>
          <p class="xs-col">Boats Group — Miami, FL — Remote</p>
          <p class="xs-col">March 2022 — May 2024 — Full-time</p>
        </hgroup>
        <section class="xs-col">
          <ul class="xs-col">
            <li>
              <p>This role heavily revolved around the product and feature development of key projects, including:</p>
              <ul>
                <li>Updating the ad prebid API to use updated GEO location data, as well as writing a cronjob to update ad prebid data regularly, from a third-party source.</li>
                <li>Helping to deliver CAS updates to support SSO for employees.</li>
                <li>Created a new React web app that replaced a legacy lead delivery tool (Java) for clients.</li>
                <li>Wrote archiving procedures to remove massive amounts of outdated and irrelevant rows (1-billion+ across a dozen or so tables), which greatly boosted the performance of MySQL queries, and over a half-dozen Java services and monolithic web apps.</li>
                <li>UI redesigns of admin and inventory management pages (monolithic Java + Grails web app).</li>
              </ul>
            </li>
            <li>Supported the training and onboarding of new team members.</li>
            <li>Later this role saw a shift to a healthy mix of feature and M&S work (Node.js and Java maintenance).</li>
            <li>Tasked with bug hunting and squashing for escalated — high-priority — tickets.</li>
            <li>Identified additional poor performance in MySQL queries and added a few indices to help alleviate these issues.</li>
            <li>Helped to identify timezone issues (PST vs. UTC) between web apps and sources of truth.</li>
            <li>Upgraded a half-dozen Node.js 14.x and 10.x projects (APIs, libraries, and web apps) to Node.js 20.</li>
          </ul>
        </section>
      </article>

      <article class="xs-col">
        <hgroup class="xs-col text-center">
          <h3 class="xs-col">Software Developer</h3>
          <p class="xs-col">Boats Group — Miami, FL — On-site</p>
          <p class="xs-col">March 2019 — March 2022 — Full-time</p>
        </hgroup>
        <section class="xs-col">
          <ul class="xs-col">
            <li>This role saw me shift to predominately an M&S workload in Node.js APIs; but also some monolithic Java web apps (Grails and custom frameworks).</li>
            <li>
              <p>Wrote a new RESTful inventory API (Node.js + @hapi/hapi), which surfaced — both internally to our systems and externally to customers (using Kong API Gateway) — data indexed into Elasticsearch. This included:</p>
              <ul>
                <li>Creating a SQS queue to enqueue inventory items that need to be indexed.</li>
                <li>Creating a Lambda to digest the aforementioned queue and put items into Elasticsearch.</li>
                <li>Creating a DLQ to handle failures in the aforementioned Lambda.</li>
                <li>Creating CloudWatch alarms to watch for failures end-to-end.</li>
                <li>Creating all aforementioned infrastructure using Terraform (IaC).</li>
                <li>Creating Jenkins jobs for deployment of API and Lambda to QA and Production environments.</li>
                <li>Refactoring of pre-existing internal systems to ensure compatibility with changes.</li>
              </ul>
            </li>
            <li>Began full-time remote work in early 2020.</li>
            <li>Later in this team — much like my time in UI Development — I took on a lead developer role, managing ticket backlogs (preparation, prioritization, etc.), as well as leading some team meetings when our development manager was otherwise preoccupied.</li>
            <li>Upgraded dozens of Node.js 0.x, 4.x, and 10.x projects (APIs, libraries, and web apps) to Node.js 14.</li>
          </ul>
        </section>
      </article>

      <article class="xs-col">
        <hgroup class="xs-col text-center">
          <h3 class="xs-col">UI Developer</h3>
          <p class="xs-col">Boats Group — Miami, FL — On-site</p>
          <p class="xs-col">July 2017 — March 2019 — Full-time</p>
        </hgroup>
        <section class="xs-col">
          <ul class="xs-col">
            <li>Worked hand-in-hand with the backend development team to generate SASS templates for a WordPress custom multisite platform that serviced 500+ customer websites.</li>
            <li>Pushed for new standards (component reusability, HTML5 semantics, CSS3 pseudo-selectors, SASS variables/functions/mixins, etc.) to be enforced.</li>
            <li>Later became a full-stack developer in this team, working on the custom WordPress platform (PHP / Zend framework), integrating a new inventory API, and contributing to many of the custom WordPress plugins.</li>
            <li>Performed maintenance on the website generator tool (Node.js + Express) when it fell over and the knowledge from previous developers was no longer available.</li>
            <li>
              <p>Began leading a small development team of four as the company grew and the platform implementation team expanded. This included responsibilities like:</p>
              <ul>
                <li>Ticket creation (Jira) for upcoming projects.</li>
                <li>Organizing team meetings to review tickets before upcoming sprints.</li>
                <li>Leading biweekly sprint review calls.</li>
                <li>Deliverying team 'Wins' at our weekly, 'Fridays are for Winners' meetings.</li>
              </ul>
            </li>
          </ul>
        </section>
      </article>

      <article class="xs-col">
        <hgroup class="xs-col text-center">
          <h3 class="xs-col">Technical Support Representative</h3>
          <p class="xs-col">Boats Group — Miami, FL — On-site</p>
          <p class="xs-col">June 2017 — July 2017 — Full-time</p>
        </hgroup>
        <section class="xs-col">
          <ul class="xs-col">
            <li>Helped to maintain a ticket queue of customer and employee issues across the entire ecosystem of the company.</li>
            <li>Many tickets required reading [and updating] KB articles, communication across account managers, development teams and managers, and product owners, and a lot of MySQL entries.</li>
          </ul>
        </section>
      </article>

      <article class="xs-col">
        <hgroup class="xs-col text-center">
          <h3 class="xs-col">Custom WordPress Developer</h3>
          <p class="xs-col">1to1 Kitchen and Bath — Orlando, FL — Hybrid</p>
          <p class="xs-col">April 2017 — June 2017 — Freelance</p>
        </hgroup>
        <section class="xs-col">
          <ul class="xs-col">
            <li>
              <p>Managed a custom WordPress site for a small business.</p>
              <ul>
                <li>Added new articles, eCommerce plugins, products, and [responsive] images.</li>
                <li>Resolved style issues across viewports using responsive web development standards.</li>
              </ul>
            </li>
            <li>Managed expectations with a very satisfied business owner.</li>
          </ul>
        </section>
      </article>

      <article class="xs-col">
        <hgroup class="xs-col text-center">
          <h3 class="xs-col">Lead Back-end Developer</h3>
          <p class="xs-col">Bilder — Greater Chicago Area — Remote</p>
          <p class="xs-col">June 2016 — March 2017 — Freelance</p>
        </hgroup>
        <section class="xs-col">
          <ul class="xs-col">
            <li>A unique crowd-funding platform for universities, their students, and their communities.</li>
            <li>Planned, developed, and maintained back-end architecture for web app.</li>
            <li>Created database schemas (MongoDB) to store projects, users, funding, etc.</li>
            <li>Created a secured RESTful API (Node.js + Express) to surface stored data safely.</li>
            <li>Helped implement an algorithm, to determine contributor impact across projects, based on GEO location.</li>
            <li>Worked closely with the design and front-end teams, especially during the planning stages, to ensure API payloads (input and output) would only accept correct and relevant data.</li>
          </ul>
        </section>
      </article>

      <article class="xs-col">
        <hgroup class="xs-col text-center">
          <h3 class="xs-col">Full-stack Web Developer and DB Admin</h3>
          <p class="xs-col">ContegoPrint — Remote</p>
          <p class="xs-col">April 2012 — December 2014 — Freelance</p>
        </hgroup>
        <section class="xs-col">
          <ul class="xs-col">
            <li>A SaaS and eCommerce platform that allowed for the management and sale of author-published eBooks.</li>
            <li>Helped to develop a patented procedure to protect the integrity of eBooks made available on the platform.</li>
            <li>Created and managed database schemas (MySQL) to store authors, eBooks, authentication codes, customers, sales, etc.</li>
            <li>
              <p>Designed and developed the front-facing web apps (PHP, MVC, CSS3, jQuery, MySQL, PDO):</p>
              <ul>
                <li>Company website.</li>
                <li>Sales and inventory portals for customers.</li>
                <li>eBook management portal for authors (CRUD app with PayPal Store integration).</li>
                <li>Responsible for eBook authorization key generation, storage security (MD5 + random hash), and delivery after purchase.</li>
              </ul>
            </li>
          </ul>
        </section>
      </article>

    </main>
  </section>

  <section class="xs-col no-print">
    <hgroup class="xs-col text-center text-uppercase">
      <h2 class="xs-col">View this — and My Site — Online!</h2>
    </hgroup>
    <section class="xs-col">
      <img class="xs-col" src="/images/templates/zeiglerd-theme/views/page/resume-qr-code.svg" alt="QR code" />
    </section>
    <section class="xs-col">
      <p class="break-word text-center">Or check-out the source code on GitHub:<br><a href="https://github.com/zeiglerd/zeiglerd.com/tree/main/src/templates/zeiglerd-theme/views/page">https://github.com/zeiglerd/zeiglerd.com/tree/main<br>/src/templates/zeiglerd-theme/views/page</a></p>
    </section>
  </section>

  <section class="xs-col">
    <section class="xs-col">
      <p class="xs-col text-right">v3.3.0</p>
    </section>
  </section>

</article>
<?php $this->renderPartial('footer'); ?>
<?php $this->renderPartial('foot'); ?>
