<?php $this->renderPartial('head'); ?>
<?php $this->renderPartial('header'); ?>
<article data-page="post-resume">

  <section class="xs-col">
    <hgroup class="xs-col text-center">
      <h1 class="xs-col">Dustin Zeigler</h1>
      <p class="xs-col">Senior Software Developer</p>
    </hgroup>
  </section>

  <section class="xs-col">
    <hgroup class="xs-col text-center text-uppercase">
      <h2 class="xs-col">Profile</h2>
    </hgroup>
    <section class="xs-col">
      <p class="xs-col text-center">Software developer with 7 years of industry experience working as a full-stack web developer within a JavaScript environment, leveraging IaC and cloud-based computing for infrastructure solutions, MySQL for storage, and Elasticsearch for indexing, and working alongside front-end designers to create web applications utilizing HTML5, CSS3, and JS.</p>
    </section>
  </section>

  <section class="xs-col md-row">
    <aside class="xs-col md-col-1">

      <section class="xs-col">
        <hgroup class="xs-col text-center text-uppercase">
          <h2 class="xs-col">Contact</h2>
        </hgroup>
        <section class="xs-col">
          <address class="xs-col font-normal">
            <ul class="xs-col list-style-none">
              <li><a href="tel:+15737895757">+1 (573) 789-5757</a></li>
              <li><a href="mailto:dustin.zeigler@live.com">dustin.zeigler@live.com</a></li>
              <li>1307 Sandra Ave<br>Apt B<br>Warrensburg, MO. 64093</li>
              <li><a href="https://www.linkedin.com/in/zeiglerd/">https://www.linkedin.com/in/zeiglerd/</a></li>
            </ul>
          </address>
        </section>
      </section>

      <section class="xs-col">
        <hgroup class="xs-col text-center text-uppercase">
          <h2 class="xs-col">Education</h2>
        </hgroup>
        <section class="xs-col">
          <ul class="xs-col list-style-none">
            <li>
              <hgroup class="xs-col text-center">
                <p class="xs-col">February 2017</p>
                <h3 class="xs-col">BSc Web Design and Development</h3>
                <p class="xs-col">Full Sail University</p>
              </hgroup>
            </li>
          </ul>
        </section>
      </section>

      <section class="xs-col">
        <hgroup class="xs-col text-center text-uppercase">
          <h2 class="xs-col">Key Skills</h2>
        </hgroup>
        <section class="xs-col">
          <p class="xs-col">7 years of industry experience with the following:</p>
          <ul class="xs-col">
            <li>JavaScript (TS, ECMAScript, CJS)</li>
            <li>Node.js (exports, @hapi/hapi, Express, Lodash)</li>
            <li>OpenAPI for API Specification</li>
            <li>Unit Testing (@hapi/lab and @hapi/code, and others)</li>
            <li>
              <p>React<p>
              <ul>
                <li>Application Lifecycle</li>
                <li>Functional Components</li>
                <li>State Management</li>
                <li>SSR</li>
              </ul>
            </li>
            <li>HTML5 Semantics</li>
            <li>SASS and CSS3</li>
            <li>jQuery and AJAX (when not in React)</li>
            <li>
              <p>AWS Infrastructure Solutions Involving</p>
              <ul>
                <li>API Gateway</li>
                <li>Batch</li>
                <li>EC2</li>
                <li>ECS</li>
                <li>Lambda</li>
                <li>RDS</li>
                <li>S3</li>
                <li>SNS</li>
                <li>SQS</li>
                <li>SSM</li>
              </ul>
            </li>
            <li>Memcached</li>
            <li>MySQL Databases</li>
            <li>NoSQL Databases</li>
            <li>Elasticsearch Indices</li>
            <li>Git for Source Control</li>
            <li>Agile Development Processes</li>
            <li>Feature Branch Workflow</li>
            <li>Test Driven Design</li>
          </ul>
        </section>
      </section>

      <section class="xs-col">
        <hgroup class="xs-col text-center text-uppercase">
          <h2 class="xs-col">Further Skills</h2>
        </hgroup>
        <section class="xs-col">
          <p class="xs-col">Some experience with the following:</p>
          <ul class="xs-col">
            <li>
              <p>AWS</p>
              <ul>
                <li>CLI</li>
                <li>DocumentDB</li>
                <li>Security</li>
              </ul>
            </li>
            <li>Monolithic PHP Webapps and APIs (Zend and Custom Frameworks)</li>
            <li>Monolithic Java Webapps and APIs (Grails and Custom Frameworks)</li>
            <li>Regular Expressions</li>
            <li>Kong API Gateway</li>
            <li>Bash and ZSH</li>
            <li>Ubuntu Server</li>
            <li>WordPress and WordPress Multisite</li>
            <li>Leadership of a Small Development Team (4 Members)</li>
            <li>Training and Onboarding New Staff Members</li>
          </ul>
        </section>
      </section>
    </aside>

    <main class="xs-col md-col-2 lg-col-3">
      <hgroup class="xs-col text-center text-uppercase">
        <h2 class="xs-col">Professional Experience</h2>
      </hgroup>

      <article class="xs-col">
        <hgroup class="xs-col text-center">
          <h3 class="xs-col">Senior Software Developer</h3>
          <p class="xs-col">Boats Group — Miami, FL — Remote</p>
          <p class="xs-col">March 2022 — May 2024 — Full-time</p>
        </hgroup>
        <section class="xs-col">
          <ul class="xs-col">
            <li>
              <p>This role heavily revolved around the product and feature development of key projects, including:</p>
              <ul>
                <li>Updating the ad prebid API to use updated GEO location data, as well as writing a cronjob to update ad prebid data regularly, from a third-party source.</li>
                <li>Helping to deliver CAS updates to support SSO for employees.</li>
                <li>I wrote archiving procedures to remove massive amounts of irrelevant rows (1-billion+ rows across a dozen or so tables), which greatly boosted the performance of MySQL queries, and over a half-dozen Java services and monolithic web apps.</li>
                <li>UI redesigns of admin and inventory management pages (monolithic Java + Grails web app).</li>
              </ul>
            </li>
            <li>Supported the training and onboarding of new team members.</li>
            <li>Later this role saw a shift to an unbalanced workload of 70% M&S and 30% feature work (Java and Node.js maintenance).</li>
            <li>Tasked with bug hunting and squashing for escalated — high-priority — tickets.</li>
            <li>Identified additional poor performance in MySQL queries and added a few indices to help alleviate these issues.</li>
            <li>Helped to identify timezone issues (PST vs. UTC) between web apps and sources of truth.</li>
            <li>Upgraded a half-dozen Node.js 14.x and 10.x projects (APIs, libraries, and web apps) to Node.js 20.</li>
          </ul>
        </section>
      </article>

      <article class="xs-col">
        <hgroup class="xs-col text-center">
          <h3 class="xs-col">Software Developer</h3>
          <p class="xs-col">Boats Group — Miami, FL — On-site</p>
          <p class="xs-col">March 2019 — March 2022 — Full-time</p>
        </hgroup>
        <section class="xs-col">
          <ul class="xs-col">
            <li>This role saw me shift to a healthy mix of feature and M&S work, predominantly in Node.js APIs; but also some monolithic Java web apps (Grails and custom frameworks).</li>
            <li>
              <p>Wrote a new RESTful inventory API (Node.js + @hapi/hapi), which surfaced — both internally to our systems and externally to customers (using Kong API Gateway) — data indexed into Elasticsearch. This included:</p>
              <ul>
                <li>Writing IaC (Terraform) for infrastructure.</li>
                <li>Creating Jenkins jobs for deployment.</li>
                <li>Creating a SQS queue to enqueue inventory items that need to be indexed.</li>
                <li>Creating a Lambda to digest the aforementioned queue.</li>
                <li>Creating a DLQ to handle failures in the aforementioned Lambda.</li>
                <li>Creating CloudWatch alarms to watch for failures end-to-end.</li>
                <li>Refactoring of pre-existing systems to ensure compatibility with changes.</li>
              </ul>
            </li>
            <li>Began full-time remote work in early 2020.</li>
            <li>Later in this role — much like my time in UI Development — I took on a lead developer role, managing ticket backlogs (preparation, prioritization, etc.), as well as leading some team meetings when our development manager was otherwise preoccupied.</li>
            <li>Upgraded dozens of Node.js 0.x, 4.x, and 10.x projects (APIs, libraries, and web apps) to Node.js 14.</li>
          </ul>
        </section>
      </article>

      <article class="xs-col">
        <hgroup class="xs-col text-center">
          <h3 class="xs-col">UI Developer</h3>
          <p class="xs-col">Boats Group — Miami, FL — On-site</p>
          <p class="xs-col">July 2017 — March 2019 — Full-time</p>
        </hgroup>
        <section class="xs-col">
          <ul class="xs-col">
            <li>I worked hand-in-hand with the backend development team to generate SASS templates for a WordPress custom multisite platform that serviced 500+ customer websites.</li>
            <li>Pushed for new standards (reusability, HTML5 semantics, CSS3 pseudo-selectors, SASS variables/functions/mixins, etc.) to be enforced.</li>
            <li>I ended up becoming a full-stack developer in this position, working on the custom WordPress platform (PHP / Zend framework), integrating a new inventory API, and contributing to many of the custom WordPress plugins.</li>
            <li>Additionally, I worked on the website generator (Node.js + Express) when it fell over, and the knowledge from previous developers was no longer available.</li>
            <li>
              <p>I began leading a small development team of four as the company grew and the platform implementation team expanded. This included responsibilities like:</p>
              <ul>
                <li>Ticket creation (Jira) for upcoming projects.</li>
                <li>Organizing crew meetings to review tickets before upcoming sprints.</li>
                <li>Leading biweekly sprint review calls.</li>
                <li>Deliverying crew 'Wins' at our weekly, "Fridays are for Winners" meetings.</li>
              </ul>
            </li>
          </ul>
        </section>
      </article>

      <article class="xs-col">
        <hgroup class="xs-col text-center">
          <h3 class="xs-col">Technical Support Representative</h3>
          <p class="xs-col">Boats Group — Miami, FL — On-site</p>
          <p class="xs-col">June 2017 — July 2017 — Full-time</p>
        </hgroup>
        <section class="xs-col">
          <ul class="xs-col">
            <li>Helped to maintain a ticket queue of customer and employee issues across the entire ecosystem of the company.</li>
            <li>Many tickets required reading [and updating] KB articles, communication across account managers, development crews and managers, and product owners, and a lot of MySQL entries.</li>
          </ul>
        </section>
      </article>

      <article class="xs-col">
        <hgroup class="xs-col text-center">
          <h3 class="xs-col">Custom WordPress Developer</h3>
          <p class="xs-col">1to1 Kitchen and Bath — Orlando, FL — Hybrid</p>
          <p class="xs-col">April 2017 — June 2017 — Freelance</p>
        </hgroup>
        <section class="xs-col">
          <ul class="xs-col">
            <li>
              <p>Managed a custom WordPress site for a small business.</p>
              <ul>
                <li>Added new articles, eCommerce plugins, products, and [responsive] images.</li>
                <li>Resolved style issues across viewports using responsive web development standards.</li>
              </ul>
            </li>
            <li>Managed expectations with a very satisfied business owner.</li>
          </ul>
        </section>
      </article>

      <article class="xs-col">
        <hgroup class="xs-col text-center">
          <h3 class="xs-col">Lead Back-end Developer</h3>
          <p class="xs-col">Bilder — Greater Chicago Area — Remote</p>
          <p class="xs-col">June 2016 — March 2017 — Freelance</p>
        </hgroup>
        <section class="xs-col">
          <ul class="xs-col">
            <li>A unique crowd-funding platform for universities, their students, and their communities.</li>
            <li>Planned, developed, and maintained back-end architecture for web app.</li>
            <li>Created database schemas (MongoDB) to store projects, users, funding, etc.</li>
            <li>Created a secured RESTful API (Node.js + Express) to surface stored data safely.</li>
            <li>Helped implement an algorithm, to determine contributor impact across projects, based on GEO location.</li>
            <li>I worked closely with the design and front-end teams, especially during the planning stages, to ensure API payloads (input and output) would only accept correct and relevant data.</li>
          </ul>
        </section>
      </article>

      <article class="xs-col">
        <hgroup class="xs-col text-center">
          <h3 class="xs-col">Full-stack Web Developer and DB Admin</h3>
          <p class="xs-col">ContegoPrint — Remote</p>
          <p class="xs-col">April 2012 — December 2014 — Freelance</p>
        </hgroup>
        <section class="xs-col">
          <ul class="xs-col">
            <li>A SaaS and eCommerce platform that allowed for the management and sale of author-published eBooks.</li>
            <li>Helped to develop a patented procedure to protect the integrity of eBooks made available on the platform.</li>
            <li>Created and managed database schemas (MySQL) to store authors, eBooks, authentication codes, customers, sales, etc.</li>
            <li>
              <p>Designed and developed the front-facing web apps (PHP, MVC, CSS3, jQuery, MySQL, PDO):</p>
              <ul>
                <li>Company website.</li>
                <li>Sales and inventory portals for customers.</li>
                <li>eBook management portal for authors (CRUD app with PayPal Store integration).</li>
                <li>Responsible for eBook authorization key generation, storage security (MD5 + random hash), and delivery after purchase.</li>
              </ul>
            </li>
          </ul>
        </section>
      </article>

    </main>
  </section>

  <section class="xs-col no-print">
    <hgroup class="text-center text-uppercase">
      <h2 class="xs-col">View this — and My Site — Online!</h2>
    </hgroup>
    <section class="xs-col">
      <img class="xs-col" src="/images/templates/zeiglerd-theme/views/post/resume-qr-code.svg" alt="QR code" />
    </section>
    <section>
      <p>Or you can check out the source code on Github:<br><a href="https://github.com/zeiglerd/zeiglerd.com/tree/main/src/templates/zeiglerd-theme/views/post">https://github.com/zeiglerd/zeiglerd.com/tree/main/src/templates/zeiglerd-theme/views/post</a>!</p>
    </section>
  </section>

  <section class="xs-col">
    <section class="xs-col">
      <p class="xs-col text-right">v3.1.7</p>
    </section>
  </section>
</article>
<?php $this->renderPartial('footer'); ?>
<?php $this->renderPartial('foot'); ?>
