<header class="xxs-col">
  <nav class="xxs-col-1">
    <header class="xxs-row-1">
      <hgroup class="xxs-col-1">
        <h1><a href="<?= $this->t->Helpers::getLink(); ?>" rel="home"><?= PROJECT_NAME; ?></a></h1>
      </hgroup>
      <button class="xxs-col" title="Navigation Menu">
        <div></div>
        <div></div>
        <div></div>
      </button>
    </header>
    <menu class="xxs-col hidden">
      <li><a href="<?= $this->t->Helpers::getLink('games/cheddar'); ?>">Cheddar</a></li>
      <li><a href="<?= $this->t->Helpers::getLink('games/geordie'); ?>">Geordie</a></li>
    </menu>
  </nav>
</header>
